// Code generated by "stringer -type=CDomain"; DO NOT EDIT.

package cmn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CDomainSys-322]
	_ = x[CDomainSysAdmin-333]
	_ = x[CDomainSysMaintain-366]
	_ = x[CDomainSysUser-377]
	_ = x[CDomainSysAnonymous-388]
	_ = x[CDomainSysPromotion-561]
	_ = x[CDomainSysSale-563]
	_ = x[CDomainSysTrial-566]
	_ = x[CDomainAdmin-567]
	_ = x[CDomainMaintain-569]
	_ = x[CDomainUser-671]
	_ = x[CDomainAnonymous-673]
	_ = x[CDomainPromotion-675]
	_ = x[CDomainSale-677]
	_ = x[CDomainTrial-679]
	_ = x[CDomainQNear-1077]
	_ = x[CDomainQNearAdmin-1079]
	_ = x[CDomainAbilityIdx-1177]
	_ = x[CDomainAbilityIdxAdmin-1179]
	_ = x[CDomainForeseeLab-1277]
	_ = x[CDomainForeseeLabAdmin-1279]
	_ = x[CDomainRecruitMgr-1377]
	_ = x[CDomainRecruitMgrAdmin-1379]
	_ = x[CDomainJXDD-1477]
	_ = x[CDomainJXDDAdmin-1479]
	_ = x[CDomainDonate-1577]
	_ = x[CDomainDonateAdmin-1579]
	_ = x[CDomainXKB-10002]
	_ = x[CDomainXKBAdmin-10004]
	_ = x[CDomainXKBSale-10006]
	_ = x[CDomainXKBSchoolAdmin-10008]
	_ = x[CDomainXKBSchoolStatistics-10010]
	_ = x[CDomainXKBUser-10012]
	_ = x[CDomainXKBPromotion-10016]
	_ = x[CDomainXKBFE-10020]
	_ = x[CDomainXKBBE-10030]
	_ = x[CDomainAssess-10098]
	_ = x[CDomainAssessAdmin-10100]
	_ = x[CDomainAssessLeader-10102]
	_ = x[CDomainAssessFacultyAdmin-10104]
	_ = x[CDomainAssessAcademicAffairDean-10106]
	_ = x[CDomainAssessStudentAffairDean-10108]
	_ = x[CDomainAssessFacultyLeader-10110]
	_ = x[CDomainAssessAcademicAffairAdmin-10112]
	_ = x[CDomainAssessTeacher-10114]
	_ = x[CDomainAssessExamSupervisor-10116]
	_ = x[CDomainAssessExamGrader-10118]
	_ = x[CDomainAssessScoreChecker-10120]
	_ = x[CDomainAssessExamSite-10122]
	_ = x[CDomainAssessExamSiteAdmin-10124]
	_ = x[CDomainAssessMaintain-10126]
	_ = x[CDomainAssessStudent-10128]
	_ = x[CDomainCourse-10200]
	_ = x[CDomainCourseAdmin-10202]
	_ = x[CDomainCourseMaintain-10204]
	_ = x[CDomainCoursePromotion-10206]
	_ = x[CDomainCourseTeacher-10208]
	_ = x[CDomainCourseTeachingAssistant-10210]
	_ = x[CDomainCourseClassRepresentative-10212]
	_ = x[CDomainCourseStudent-10214]
	_ = x[CUserDefaultCreator-1000]
	_ = x[CUserDefaultMaintainer-1000]
	_ = x[CUserDefaultDomainID-333]
}

const _CDomain_name = "CDomainSysCDomainSysAdminCDomainSysMaintainCDomainSysUserCDomainSysAnonymousCDomainSysPromotionCDomainSysSaleCDomainSysTrialCDomainAdminCDomainMaintainCDomainUserCDomainAnonymousCDomainPromotionCDomainSaleCDomainTrialCUserDefaultCreatorCDomainQNearCDomainQNearAdminCDomainAbilityIdxCDomainAbilityIdxAdminCDomainForeseeLabCDomainForeseeLabAdminCDomainRecruitMgrCDomainRecruitMgrAdminCDomainJXDDCDomainJXDDAdminCDomainDonateCDomainDonateAdminCDomainXKBCDomainXKBAdminCDomainXKBSaleCDomainXKBSchoolAdminCDomainXKBSchoolStatisticsCDomainXKBUserCDomainXKBPromotionCDomainXKBFECDomainXKBBECDomainAssessCDomainAssessAdminCDomainAssessLeaderCDomainAssessFacultyAdminCDomainAssessAcademicAffairDeanCDomainAssessStudentAffairDeanCDomainAssessFacultyLeaderCDomainAssessAcademicAffairAdminCDomainAssessTeacherCDomainAssessExamSupervisorCDomainAssessExamGraderCDomainAssessScoreCheckerCDomainAssessExamSiteCDomainAssessExamSiteAdminCDomainAssessMaintainCDomainAssessStudentCDomainCourseCDomainCourseAdminCDomainCourseMaintainCDomainCoursePromotionCDomainCourseTeacherCDomainCourseTeachingAssistantCDomainCourseClassRepresentativeCDomainCourseStudent"

var _CDomain_map = map[CDomain]string{
	322:   _CDomain_name[0:10],
	333:   _CDomain_name[10:25],
	366:   _CDomain_name[25:43],
	377:   _CDomain_name[43:57],
	388:   _CDomain_name[57:76],
	561:   _CDomain_name[76:95],
	563:   _CDomain_name[95:109],
	566:   _CDomain_name[109:124],
	567:   _CDomain_name[124:136],
	569:   _CDomain_name[136:151],
	671:   _CDomain_name[151:162],
	673:   _CDomain_name[162:178],
	675:   _CDomain_name[178:194],
	677:   _CDomain_name[194:205],
	679:   _CDomain_name[205:217],
	1000:  _CDomain_name[217:236],
	1077:  _CDomain_name[236:248],
	1079:  _CDomain_name[248:265],
	1177:  _CDomain_name[265:282],
	1179:  _CDomain_name[282:304],
	1277:  _CDomain_name[304:321],
	1279:  _CDomain_name[321:343],
	1377:  _CDomain_name[343:360],
	1379:  _CDomain_name[360:382],
	1477:  _CDomain_name[382:393],
	1479:  _CDomain_name[393:409],
	1577:  _CDomain_name[409:422],
	1579:  _CDomain_name[422:440],
	10002: _CDomain_name[440:450],
	10004: _CDomain_name[450:465],
	10006: _CDomain_name[465:479],
	10008: _CDomain_name[479:500],
	10010: _CDomain_name[500:526],
	10012: _CDomain_name[526:540],
	10016: _CDomain_name[540:559],
	10020: _CDomain_name[559:571],
	10030: _CDomain_name[571:583],
	10098: _CDomain_name[583:596],
	10100: _CDomain_name[596:614],
	10102: _CDomain_name[614:633],
	10104: _CDomain_name[633:658],
	10106: _CDomain_name[658:689],
	10108: _CDomain_name[689:719],
	10110: _CDomain_name[719:745],
	10112: _CDomain_name[745:777],
	10114: _CDomain_name[777:797],
	10116: _CDomain_name[797:824],
	10118: _CDomain_name[824:847],
	10120: _CDomain_name[847:872],
	10122: _CDomain_name[872:893],
	10124: _CDomain_name[893:919],
	10126: _CDomain_name[919:940],
	10128: _CDomain_name[940:960],
	10200: _CDomain_name[960:973],
	10202: _CDomain_name[973:991],
	10204: _CDomain_name[991:1012],
	10206: _CDomain_name[1012:1034],
	10208: _CDomain_name[1034:1054],
	10210: _CDomain_name[1054:1084],
	10212: _CDomain_name[1084:1116],
	10214: _CDomain_name[1116:1136],
}

func (i CDomain) String() string {
	if str, ok := _CDomain_map[i]; ok {
		return str
	}
	return "CDomain(" + strconv.FormatInt(int64(i), 10) + ")"
}
